apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  labels:
    app.kubernetes.io/name: backend
spec:
  rules:
  - host: backend.rancher.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: backend-service
            port:
              number: 3000
  tls:
  - hosts:
    - backend.rancher.localhost
    - backend.kubernetes.docker.internal
