apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-namespace.yaml
- backend-deployment.yaml
- backend-service.yaml
- backend-ingress.yaml
- yf-deployment.yaml
- yf-service.yaml
- redis-deployment.yaml
- redis-service.yaml
- kev-deployment.yaml
- kev-service.yaml
- tika-deployment.yaml
- tika-service.yaml
namespace: backend
images:
- name: backend
  newName: ip999/backend
  newTag: 0.0.28
