apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-namespace.yaml
- backend-deployment.yaml
- backend-service.yaml
- backend-ingress.yaml
namespace: backend
images:
- name: backend
  newName: ip999/backend
  newTag: 4.6.0
