apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
- backend-namespace.yaml
namespace: backend
images:
- name: backend
  newName: ip999/backend
  newTag: 739e5fa81841dd6e79a8de1839eadb5b2bb8039f
