# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic-Example CI

on:
  push:
    branches: ["main"]
    paths:
      - basic-example/**
  pull_request:
    branches: ["main"]
    paths:
      - basic-example/**

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: 🧪 Initial Tests
    runs-on: ${{ matrix.os}}
    defaults:
      run:
        working-directory: ./basic-example
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Jest
        run: yarn global add jest
      - name: Run tests
        run: yarn test
