# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - basic-example/**
  pull_request:
    branches: [ "main" ]
    paths:
      - basic-example/**

jobs:
  Test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./basic-example
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - run: jest
